### ISSUE TITLE
Adicionar licença livre

### ISSUE THREAD

**Issue by pizzamaker** [mhaddad/SimplePresenter#3]
Faltou especificar no projeto uma licença. Minha sugestão: criar um arquivo de texto tipo COPYING.md ou LICENSE.md com o texto da licença AGPLv3: https://www.gnu.org/licenses/agpl.html

**Comment by gustavovnicius** [comment]
Adicionado @pizzamaker. Só por curiosidade, que vai fazer?

**Comment by pizzamaker** [comment]
@gustavovnicius incentivar a realização do #4 :)
